services:
  traefik:
    stack: routing
    enabled: true
    replicas: 1

  radarr:
    stack: media
    enabled: true

  sonarr:
    stack: media
    enabled: true

  qbittorrent:
    stack: media
    enabled: true

  prowlarr:
    stack: media
    enabled: true

  tattoo-app:
    stack: apps
    enabled: true
