@echo off
echo 🛑 [RESET] Stopping all M3TAL stacks...

echo [1/6] Control Plane...
docker compose -f control-plane\docker-compose.yml down --remove-orphans

echo [2/6] Routing...
docker compose -f docker\routing\docker-compose.yml down --remove-orphans

echo [3/6] Maintenance...
docker compose -f docker\maintenance\docker-compose.yml down --remove-orphans

echo [4/6] Media...
docker compose -f docker\media\docker-compose.yml down --remove-orphans

echo [5/6] Network...
docker compose -f docker\network\docker-compose.yml down --remove-orphans

echo [6/6] Tattoo App...
docker compose -f docker\apps\tattoo-app\docker-compose.yml down --remove-orphans

echo 🧹 [CLEAN] Pruning disconnected Docker networks...
docker network prune -f

echo 🚀 [START] Re-launching core infrastructure...

echo [1/3] Proxy Network...
docker network create proxy 2>nul || echo (Proxy network already exists)

echo [2/3] Routing (Traefik/Cloudflared)...
docker compose -f docker\routing\docker-compose.yml up -d

echo [3/3] Control Plane Runtime...
docker compose -f control-plane\docker-compose.yml up -d

echo ✅ [DONE] Infrastructure redeployed with hardened networking contracts.
echo 👉 Run 'm3tal audit' to verify environment state.
